import pytest

from src.game.hand import Hand, Meld
from src.game.rules import YakuChecker
from tiles.tile import Dragon, Suit, Tile, Wind


def _hand(tiles, *, melds=None, riichi=False, riichi_turn=None, ippatsu=False):
    hand = Hand()
    hand.concealed_tiles = list(tiles)
    hand.melds = list(melds or [])
    hand.is_riichi = riichi
    hand.riichi_turn = riichi_turn
    hand.ippatsu_eligible = ippatsu
    return hand


def _names(hand, winning_tile, *, is_tsumo, **ctx):
    yaku = YakuChecker.check_all_yaku(
        hand=hand,
        winning_tile=winning_tile,
        is_tsumo=is_tsumo,
        seat_wind=Wind.EAST,
        round_wind=Wind.SOUTH,
        dora_tiles=[],
        ura_dora_tiles=[],
        **ctx,
    )
    return {item.name for item in yaku}


def test_double_riichi_and_ippatsu_detection():
    hand = _hand(
        [
            Tile(Suit.SOUZU, 2),
            Tile(Suit.SOUZU, 3),
            Tile(Suit.SOUZU, 4),
            Tile(Suit.PINZU, 3),
            Tile(Suit.PINZU, 4),
            Tile(Suit.PINZU, 5),
            Tile(Suit.MANZU, 4),
            Tile(Suit.MANZU, 5),
            Tile(Suit.SOUZU, 6),
            Tile(Suit.SOUZU, 7),
            Tile(Suit.SOUZU, 8),
            Tile(Suit.PINZU, 2),
            Tile(Suit.PINZU, 2),
        ],
        riichi=True,
        riichi_turn=0,
        ippatsu=True,
    )
    names = _names(
        hand,
        Tile(Suit.MANZU, 6),
        is_tsumo=True,
        is_double_riichi=True,
        is_ippatsu=True,
    )
    assert "Double Riichi" in names
    assert "Ippatsu" in names
    assert "Riichi" not in names


def test_base_yaku_set_detection():
    hand = _hand(
        [
            Tile(Suit.SOUZU, 2),
            Tile(Suit.SOUZU, 3),
            Tile(Suit.SOUZU, 4),
            Tile(Suit.PINZU, 3),
            Tile(Suit.PINZU, 4),
            Tile(Suit.PINZU, 5),
            Tile(Suit.MANZU, 4),
            Tile(Suit.MANZU, 5),
            Tile(Suit.SOUZU, 6),
            Tile(Suit.SOUZU, 7),
            Tile(Suit.SOUZU, 8),
            Tile(Suit.PINZU, 2),
            Tile(Suit.PINZU, 2),
        ]
    )
    names = _names(hand, Tile(Suit.MANZU, 6), is_tsumo=True)
    assert {"Menzen Tsumo", "Tanyao", "Pinfu"}.issubset(names)


def test_iipeikou_and_ryanpeikou_detection():
    iipeikou_hand = _hand(
        [
            Tile(Suit.MANZU, 1),
            Tile(Suit.MANZU, 2),
            Tile(Suit.MANZU, 3),
            Tile(Suit.MANZU, 1),
            Tile(Suit.MANZU, 2),
            Tile(Suit.MANZU, 3),
            Tile(Suit.PINZU, 4),
            Tile(Suit.PINZU, 5),
            Tile(Suit.PINZU, 6),
            Tile(Suit.SOUZU, 7),
            Tile(Suit.SOUZU, 8),
            Tile(Suit.SOUZU, 9),
            Tile(Suit.MANZU, 5),
        ]
    )
    iipeikou_names = _names(iipeikou_hand, Tile(Suit.MANZU, 5), is_tsumo=True)
    assert "Iipeikou" in iipeikou_names

    ryanpeikou_hand = _hand(
        [
            Tile(Suit.MANZU, 1),
            Tile(Suit.MANZU, 2),
            Tile(Suit.MANZU, 3),
            Tile(Suit.MANZU, 1),
            Tile(Suit.MANZU, 2),
            Tile(Suit.MANZU, 3),
            Tile(Suit.PINZU, 7),
            Tile(Suit.PINZU, 8),
            Tile(Suit.PINZU, 9),
            Tile(Suit.PINZU, 7),
            Tile(Suit.PINZU, 8),
            Tile(Suit.PINZU, 9),
            Tile(Suit.SOUZU, 5),
        ]
    )
    ryanpeikou_names = _names(ryanpeikou_hand, Tile(Suit.SOUZU, 5), is_tsumo=True)
    assert "Ryanpeikou" in ryanpeikou_names
    assert "Iipeikou" not in ryanpeikou_names


@pytest.mark.parametrize(
    "expected_name,tiles,winning,is_tsumo,melds,ctx",
    [
        (
            "Chiitoitsu",
            [
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.PINZU, 3),
                Tile(Suit.PINZU, 4),
                Tile(Suit.PINZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 6),
                Tile(Suit.MANZU, 6),
                Tile(Suit.WIND, wind=Wind.EAST),
            ],
            Tile(Suit.WIND, wind=Wind.EAST),
            False,
            None,
            {},
        ),
        (
            "Yakuhai",
            [
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 5),
            ],
            Tile(Suit.MANZU, 5),
            False,
            None,
            {},
        ),
        (
            "Toitoi",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.PINZU, 5),
            ],
            Tile(Suit.PINZU, 5),
            False,
            [Meld([Tile(Suit.MANZU, 4)] * 3, is_open=True)],
            {},
        ),
        (
            "Sanshoku Doujun",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 6),
            True,
            None,
            {},
        ),
        (
            "Sanshoku Doukou",
            [
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 5),
                Tile(Suit.PINZU, 5),
                Tile(Suit.PINZU, 5),
                Tile(Suit.SOUZU, 5),
                Tile(Suit.SOUZU, 5),
                Tile(Suit.SOUZU, 5),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 3),
            True,
            None,
            {},
        ),
        (
            "Ittsu",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 6),
                Tile(Suit.MANZU, 7),
                Tile(Suit.MANZU, 8),
                Tile(Suit.MANZU, 9),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.SOUZU, 5),
                Tile(Suit.SOUZU, 5),
            ],
            Tile(Suit.PINZU, 3),
            True,
            None,
            {},
        ),
        (
            "Sanankou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 6),
            True,
            None,
            {},
        ),
        (
            "Sankantsu",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
            ],
            Tile(Suit.PINZU, 4),
            True,
            [
                Meld([Tile(Suit.SOUZU, 2)] * 4, is_open=True),
                Meld([Tile(Suit.SOUZU, 3)] * 4, is_open=True),
                Meld([Tile(Suit.SOUZU, 4)] * 4, is_open=True),
            ],
            {},
        ),
        (
            "Chanta",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 8),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
            ],
            Tile(Suit.PINZU, 9),
            True,
            None,
            {},
        ),
        (
            "Junchan",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 8),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 1),
            ],
            Tile(Suit.PINZU, 9),
            True,
            None,
            {},
        ),
        (
            "Honroutou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 9),
                Tile(Suit.PINZU, 9),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 9),
                Tile(Suit.SOUZU, 9),
                Tile(Suit.WIND, wind=Wind.EAST),
            ],
            Tile(Suit.WIND, wind=Wind.EAST),
            False,
            None,
            {},
        ),
        (
            "Shousangen",
            [
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 8),
                Tile(Suit.PINZU, 9),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
            ],
            Tile(Suit.DRAGON, dragon=Dragon.RED),
            True,
            None,
            {},
        ),
        (
            "Honitsu",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 6),
                Tile(Suit.MANZU, 7),
                Tile(Suit.MANZU, 8),
                Tile(Suit.MANZU, 9),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.MANZU, 1),
            ],
            Tile(Suit.MANZU, 1),
            True,
            None,
            {},
        ),
        (
            "Chinitsu",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 6),
                Tile(Suit.MANZU, 7),
                Tile(Suit.MANZU, 8),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
            ],
            Tile(Suit.MANZU, 2),
            True,
            None,
            {},
        ),
        (
            "Rinshan Kaihou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 6),
            True,
            None,
            {"is_rinshan": True},
        ),
        (
            "Chankan",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 6),
            False,
            None,
            {"is_chankan": True},
        ),
        (
            "Haitei Raoyue",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 6),
            True,
            None,
            {"is_haitei": True},
        ),
        (
            "Houtei Raoyui",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 3),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.PINZU, 7),
                Tile(Suit.PINZU, 7),
            ],
            Tile(Suit.MANZU, 6),
            False,
            None,
            {"is_houtei": True},
        ),
    ],
)
def test_full_standard_yaku_coverage(
    expected_name, tiles, winning, is_tsumo, melds, ctx
):
    hand = _hand(tiles, melds=melds)
    names = _names(hand, winning, is_tsumo=is_tsumo, **ctx)
    assert expected_name in names


@pytest.mark.parametrize(
    "expected_name,tiles,winning,is_tsumo,melds,ctx",
    [
        (
            "Kokushi Musou",
            [
                Tile(Suit.SOUZU, 1),
                Tile(Suit.SOUZU, 1),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 9),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 9),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.NORTH),
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
            ],
            Tile(Suit.SOUZU, 9),
            False,
            None,
            {},
        ),
        (
            "Suuankou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 4),
                Tile(Suit.PINZU, 5),
                Tile(Suit.PINZU, 5),
            ],
            Tile(Suit.MANZU, 4),
            True,
            None,
            {},
        ),
        (
            "Daisangen",
            [
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.WHITE),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 1),
            ],
            Tile(Suit.MANZU, 3),
            True,
            None,
            {},
        ),
        (
            "Suukantsu",
            [Tile(Suit.WIND, wind=Wind.EAST)],
            Tile(Suit.WIND, wind=Wind.EAST),
            True,
            [
                Meld([Tile(Suit.MANZU, 1)] * 4, is_open=True),
                Meld([Tile(Suit.MANZU, 2)] * 4, is_open=True),
                Meld([Tile(Suit.MANZU, 3)] * 4, is_open=True),
                Meld([Tile(Suit.MANZU, 4)] * 4, is_open=True),
            ],
            {},
        ),
        (
            "Tsuuiisou",
            [
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.RED),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
            ],
            Tile(Suit.DRAGON, dragon=Dragon.GREEN),
            True,
            None,
            {},
        ),
        (
            "Chinroutou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 1),
                Tile(Suit.PINZU, 9),
                Tile(Suit.PINZU, 9),
                Tile(Suit.PINZU, 9),
                Tile(Suit.SOUZU, 1),
            ],
            Tile(Suit.SOUZU, 1),
            True,
            None,
            {},
        ),
        (
            "Ryuuiisou",
            [
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 4),
                Tile(Suit.SOUZU, 4),
                Tile(Suit.SOUZU, 4),
                Tile(Suit.SOUZU, 6),
                Tile(Suit.SOUZU, 6),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
                Tile(Suit.DRAGON, dragon=Dragon.GREEN),
            ],
            Tile(Suit.SOUZU, 6),
            True,
            None,
            {},
        ),
        (
            "Chuuren Poutou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
                Tile(Suit.MANZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 5),
                Tile(Suit.MANZU, 7),
                Tile(Suit.MANZU, 8),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
                Tile(Suit.MANZU, 9),
            ],
            Tile(Suit.MANZU, 6),
            True,
            None,
            {},
        ),
        (
            "Shousuushii",
            [
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.NORTH),
                Tile(Suit.WIND, wind=Wind.NORTH),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 2),
            ],
            Tile(Suit.MANZU, 3),
            True,
            None,
            {},
        ),
        (
            "Daisuushii",
            [
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.EAST),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.SOUTH),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.WEST),
                Tile(Suit.WIND, wind=Wind.NORTH),
                Tile(Suit.WIND, wind=Wind.NORTH),
                Tile(Suit.WIND, wind=Wind.NORTH),
                Tile(Suit.MANZU, 5),
            ],
            Tile(Suit.MANZU, 5),
            True,
            None,
            {},
        ),
        (
            "Tenhou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 4),
                Tile(Suit.PINZU, 5),
                Tile(Suit.PINZU, 5),
            ],
            Tile(Suit.MANZU, 4),
            True,
            None,
            {"is_tenhou": True},
        ),
        (
            "Chiihou",
            [
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.MANZU, 1),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.PINZU, 2),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.SOUZU, 3),
                Tile(Suit.MANZU, 4),
                Tile(Suit.MANZU, 4),
                Tile(Suit.PINZU, 5),
                Tile(Suit.PINZU, 5),
            ],
            Tile(Suit.MANZU, 4),
            True,
            None,
            {"is_chiihou": True},
        ),
    ],
)
def test_full_yakuman_coverage(expected_name, tiles, winning, is_tsumo, melds, ctx):
    hand = _hand(tiles, melds=melds)
    names = _names(hand, winning, is_tsumo=is_tsumo, **ctx)
    assert expected_name in names


def test_yakuman_result_suppresses_non_yakuman_and_dora():
    hand = _hand(
        [
            Tile(Suit.SOUZU, 1),
            Tile(Suit.SOUZU, 1),
            Tile(Suit.PINZU, 1),
            Tile(Suit.PINZU, 9),
            Tile(Suit.MANZU, 1),
            Tile(Suit.MANZU, 9),
            Tile(Suit.WIND, wind=Wind.EAST),
            Tile(Suit.WIND, wind=Wind.SOUTH),
            Tile(Suit.WIND, wind=Wind.WEST),
            Tile(Suit.WIND, wind=Wind.NORTH),
            Tile(Suit.DRAGON, dragon=Dragon.WHITE),
            Tile(Suit.DRAGON, dragon=Dragon.GREEN),
            Tile(Suit.DRAGON, dragon=Dragon.RED),
        ],
        riichi=True,
        riichi_turn=0,
        ippatsu=True,
    )
    yaku = YakuChecker.check_all_yaku(
        hand=hand,
        winning_tile=Tile(Suit.SOUZU, 9),
        is_tsumo=False,
        seat_wind=Wind.EAST,
        round_wind=Wind.SOUTH,
        dora_tiles=[Tile(Suit.SOUZU, 1)],
        ura_dora_tiles=[Tile(Suit.SOUZU, 1)],
        is_double_riichi=True,
        is_ippatsu=True,
    )
    names = {item.name for item in yaku}
    assert names == {"Kokushi Musou"}
